# file: compose.yaml
# description: Docker compose stack for simulating a supply chain attack
#
# @author: Derek Garcia
services:
  # mock npm registry
  mock-npm:
    container_name: "mock-npm"
    image: verdaccio/verdaccio:6.0
    # use temp storage instead of volume
    tmpfs:
      - /verdaccio/storage:mode=777
    healthcheck:
      test: [ "CMD", "ping", "-c", "1", "localhost" ]
      start_interval: 1s
      interval: 1s
      retries: 5
      start_period: 1s
      timeout: 5s
    networks:
      sca-net:

  # alice / developer machine
  alice:
    container_name: "alice"
    build:
      context: alice
    image: alice
    # open terminal so can access
    stdin_open: true
    tty: true
    depends_on:
      mock-npm:
        condition: service_healthy
    networks:
      sca-net:

  # mallory / bad actor machine
  mallory:
    container_name: "mallory"
    build:
      context: mallory
    image: mallory
    # open terminal so can access
    stdin_open: true
    tty: true
    depends_on:
      mock-npm:
        condition: service_healthy
    networks:
      sca-net:

networks:
  sca-net: