# Create a simple database and Flask API server to test simple SQL injects
#
# @author: Derek Garcia

services:
  # Simple Flask API
  app:
    container_name: app
    build: app
    image: flaskapp:1.0.0
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_HOST=mysql-db
      - MYSQL_PORT=3306
    depends_on:
      mysql-db:
        condition: service_healthy
    links:
      - mysql-db
    ports:
      - 5000:5000

  # Simple SQL Database
  mysql-db:
    container_name: mysql-db
    image: mysql:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=database
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10